-- +goose Up
CREATE TABLE If NOT EXISTS thread(
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE If NOT EXISTS post(
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  thread_id BIGINT(20) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  votes INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (thread_id) REFERENCES thread (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE If NOT EXISTS comment(
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  post_id BIGINT(20) NOT NULL,
  content Text NOT NULL,
  votes INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- +goose Down
DROP TABLE thread;
DROP TABLE post;
DROP TABLE comment;
